### ISSUE TITLE
Access denied on ho3d-process download link

### ISSUE THREAD

**Issue by schachtelman** [stevenlsw/Semi-Hand-Object#15]
Hi! Thank you for the amazing work.
I'm trying to train the model, but the provided download link for the preprocessed files gives me an access denied error.
Would it be possible to check this?

**Comment by stevenlsw** [comment]
Hi, you could find the HO3D here https://www.tugraz.at/institute/icg/research/team-lepetit/research-projects/hand-object-3d-pose-annotation/

**Comment by stevenlsw** [comment]
Hi, could you try the following link https://drive.google.com/file/d/1BcUNxdlPDFwvAHcs1tcvwMyhsr6nxxzR/view?usp=sharing

**Comment by schachtelman** [comment]
Thank you, the link works.

Do you happen to have an updated link for the pretrained model as well?

**Comment by stevenlsw** [comment]
Hi, the pre-trained model could be found at https://drive.google.com/file/d/1s3vIsYjiTLOKiBVBsaj8BtiNMlttEPrw/view?usp=sharing
