### ISSUE TITLE
trained-model

### ISSUE THREAD

**Issue by happyStudyOk** [stevenlsw/Semi-Hand-Object#16]
Hi,Thank you for your work. I did not have access when downloading the trained-model. Could you please resend it to me? Thank you!

**Comment by stevenlsw** [comment]
Hi, I update the pre-trained model link, you could download follow README.md.

**Comment by happyStudyOk** [comment]
Thank you very much！May I ask which versions of cuda and pytorch you are using？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevenlsw/Semi-Hand-Object"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月30日(星期六) 凌晨0:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevenlsw/Semi-Hand-Object] trained-model (Issue #16)





 
Hi, I update the pre-trained model link, you could download follow README.md.

**Comment by stevenlsw** [comment]
Hi, i think there are no specific requirements for the cuda and pytorch, pytorch version before 2.0 should work. Please let me know if this doesn't work.

**Comment by happyStudyOk** [comment]
Thank you very much. I also encountered a question about how to obtain evaluation metrics after testing. I found that I cannot use them when entering Codelab. Thank you for your answer and help.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevenlsw/Semi-Hand-Object"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月13日(星期六) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevenlsw/Semi-Hand-Object] trained-model (Issue #16)





 
Hi, i think there are no specific requirements for the cuda and pytorch, pytorch version before 2.0 should work. Please let me know if this doesn't work.

**Comment by happyStudyOk** [comment]
Thank you very much.&nbsp;This is the result I ran out of, but it's not satisfactory. Can you help me see why?


Thank you！
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "stevenlsw/Semi-Hand-Object"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月13日(星期六) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevenlsw/Semi-Hand-Object] trained-model (Issue #16)





 
Hi, i think there are no specific requirements for the cuda and pytorch, pytorch version before 2.0 should work. Please let me know if this doesn't work.

**Comment by stevenlsw** [comment]
Hi, I could not see the results attached, you should obtain the evaluation from Codelab, and evaluations are computed follow [here](https://github.com/shreyashampali/ho3d/blob/master/eval.py)

**Comment by happyStudyOk** [comment]
Thank you!
I have obtained the results, but there is a big gap between the results and yours. I don't know why, but the results are in my attachment. Thank you very much for helping me check the reasons.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevenlsw/Semi-Hand-Object"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 下午2:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevenlsw/Semi-Hand-Object] trained-model (Issue #16)





 
Hi, I could not see the results attached, you should obtain the evaluation from Codelab, and evaluations are computed follow here

**Comment by stevenlsw** [comment]
Hi, I couldn't see the attachments. Are you use the trained model?

**Comment by happyStudyOk** [comment]
Thank you for your reply! I used a training model that I ran on my own, but there is a big gap between the results and yours.This is the result.
Collecting open3d-python
&nbsp; Downloading https://files.pythonhosted.org/packages/5f/5c/a86082dc5efc3d22585e8aa22f9840667d9faa5e727b47c43137090caed4/open3d_python-0.7.0.0-cp27-cp27mu-manylinux1_x86_64.whl (3.7MB)
Requirement already satisfied: numpy in /opt/conda/lib/python2.7/site-packages (from open3d-python)
Requirement already satisfied: notebook in /opt/conda/lib/python2.7/site-packages (from open3d-python)
Collecting widgetsnbextension (from open3d-python)
&nbsp; Downloading https://files.pythonhosted.org/packages/9c/a0/ba2634cd75b7d7f8f9aeb38edf854cd6c9877ec064013a62630b4541b88f/widgetsnbextension-3.6.6-py2.py3-none-any.whl (1.6MB)
Requirement already satisfied: ipywidgets in /opt/conda/lib/python2.7/site-packages (from open3d-python)
Installing collected packages: widgetsnbextension, open3d-python
Successfully installed open3d-python-0.7.0.0 widgetsnbextension-3.6.6
Loading predictions from /tmp/codalab/tmpuf9m6O/run/input/res/pred.json
Evaluation 3D KP results:
auc=0.316, mean_kp3d_avg=4.91 cm
Evaluation 3D KP PROCRUSTES ALIGNED results:
auc=0.757, mean_kp3d_avg=1.22 cm
Evaluation 3D KP SCALE-TRANSLATION ALIGNED results:
auc=0.331, mean_kp3d_avg=4.85 cm


Evaluation 3D MESH results:
auc=0.325, mean_kp3d_avg=4.75 cm
Evaluation 3D MESH ALIGNED results:
auc=0.765, mean_kp3d_avg=1.18 cm


F-scores
***@***.*** = 0.152 	***@***.*** = 0.447
***@***.*** = 0.513 	***@***.*** = 0.916
Scores written to: /tmp/codalab/tmpuf9m6O/run/output/scores.txt
Evaluation complete.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevenlsw/Semi-Hand-Object"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevenlsw/Semi-Hand-Object] trained-model (Issue #16)





 
Hi, I couldn't see the attachments. Are you use the trained model?

**Comment by happyStudyOk** [comment]
Hello, I would like to ask why I tested using the training model you provided and the results were not good? How to solve it? Sincere thanks!、
Trying to locate the prediction file automatically ...
Found file "/tmp/codalab/tmpJQSQci/run/input/res/pred_{}.json"
Loading predictions from /tmp/codalab/tmpJQSQci/run/input/res/pred_{}.json
Evaluation 3D KP results:
auc=0.086, mean_kp3d_avg=12.73 cm
Evaluation 3D KP PROCRUSTES ALIGNED results:
auc=0.724, mean_kp3d_avg=1.38 cm
Evaluation 3D KP SCALE-TRANSLATION ALIGNED results:
auc=0.088, mean_kp3d_avg=12.40 cm


Evaluation 3D MESH results:
auc=0.049, mean_kp3d_avg=12.40 cm
Evaluation 3D MESH ALIGNED results:
auc=0.731, mean_kp3d_avg=1.35 cm


F-scores
***@***.*** = 0.037 	***@***.*** = 0.362
***@***.*** = 0.183 	***@***.*** = 0.898
Scores written to: /tmp/codalab/tmpJQSQci/run/output/scores.txt
Evaluation complete.

**Comment by happyStudyOk** [comment]
Hello, I really appreciate your contribution. May I ask how you visualized it in SemiHand? Thank you.

**Comment by stevenlsw** [comment]
Sorry i just saw the message, may i know are you testing on the HO3D V2 dataset or HO3D v3 dataset? for visualization, the easiest way is to visualize the saved meshes in meshlab, and you could see the results. Other way is to visualize the mesh in open3d: https://www.open3d.org/docs/latest/tutorial/geometry/mesh.html for your reference

**Comment by happyStudyOk** [comment]
Thank you very much！I conducted tests on HO3D V2.Also, I have another question. I couldn't find the 3D coordinates of the object in the code, I only found the 2D coordinates of the object and its confidence level coordinates. Can you share the code for obtaining the 3D coordinates of the object? Or how was it obtained? Thank you very much!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevenlsw/Semi-Hand-Object"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月3日(星期四) 下午3:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevenlsw/Semi-Hand-Object] trained-model (Issue #16)





 
Sorry i just saw the message, may i know are you testing on the HO3D V2 dataset or HO3D v3 dataset? for visualization, the easiest way is to visualize the saved meshes in meshlab, and you could see the results. Other way is to visualize the mesh in open3d: https://www.open3d.org/docs/latest/tutorial/geometry/mesh.html for your reference
