### ISSUE TITLE
How to draw joint figures in your paper?

### ISSUE THREAD

**Issue by buaacyw** [stevenlsw/Semi-Hand-Object#3]
Thanks for your great work!
I want to know how to draw joint figures in your paper. 
![image](https://user-images.githubusercontent.com/52091468/131459056-61bfba46-2f79-454d-9c20-3754726dd242.png)

When I ran your code, I find the 2d joints result (your model output "pred_joints") is below/
![image](https://user-images.githubusercontent.com/52091468/131459322-db9ecb1f-bc1e-4243-8630-e430ce2d1c04.png)
It seems like it's not in the pixel frame. I don't know how to visualize it (like joint figures in your paper).
If it's not convenient to show me your code, please just tell me the procedure to do it!
Thanks a lot!

**Comment by buaacyw** [comment]
And I don't know why but every time your model outputs different results with the same input....

**Comment by buaacyw** [comment]
Sorry, my bug.

**Comment by anilesec** [comment]
@buaacyw Did you manage to visualize?
