### ISSUE TITLE
Evaluating the model on SSV2

### ISSUE THREAD

**Issue by aligator022** [stevenlsw/Semi-Hand-Object#8]
Hi,
I am trying to perform the evaluation on SSV2 (sth-sth) dataset, I've successfully evaluated the trained model on HO3D, however, I am working on a small project for a project at the university and would like to run it on SSV2. 
Would you be able to point me in the right direction - what part of the dataloader should be changed to be able work with SSV2 and how can I do that?
Amazing work.

**Comment by stevenlsw** [comment]
Hi aligator022, to run on sth-sth, you just need to load those images of Sth-Sth dataset, you could easily change the dataset loader and crop around the hand-object.

**Comment by mm840511m** [comment]
Hi @aligator022, did you successfully evaluate the model on Something-Something V2 dataset?

**Comment by aligator022** [comment]
@stevenlsw Hi, the loaders that you've provided over the email, are they only for train/test purposes? I would like to evaluate the model and visualize on the SSV2 dataset. 

@mm840511m Unfortunately, I didn't manage to do it yet. Are you able to assist me?

**Comment by stevenlsw** [comment]
Hi, @aligator022, I am not sure what do you mean of evaluating on SSV2 given there is not GT 3D hand provided.

**Comment by aligator022** [comment]
By evaluating I mean running the code on SSV2 and getting the 3D bounding boxes of hands - I apologise if I wasn't clear enough. I will be able to project bounding boxes based on coordinates.

**Comment by aligator022** [comment]
Hi, I am currently evaluating the provided model on sth-sth video frames. I am currently running only for certain videos (1 at a time) and the model returns pred_{}.json which are hand joints (joints + verts). I am happy with getting joints too, but I was expecting a hand 3d bounding box. Is there a way of getting both?

**Comment by aligator022** [comment]
Hi, I managed to evaluate the provided model on SSV2 dataset and I do get joint predictions. Thanks.

**Comment by mm840511m** [comment]
Hi @aligator022 , sorry for the late reply. I am still trying to work on it. Is it possible for you to provide the relevant method or code? Thanks.

**Comment by aligator022** [comment]
Hi @mm840511m, sure. could you give me your email and I will forward you a data loader for SSV2 that @stevenlsw sent to me?

**Comment by mm840511m** [comment]
Hi, @aligator022, this is mm840511m , thank you for your reply. Is this
able to see my email?

aligator022 ***@***.***> 於 2022年9月2日 週五 下午3:00寫道：
